name: smart_x_academy
description: "A gorgeous, responsive mobile application for Smart X Academy. Replicates the Grade-level courses hub, multilingual support, light/dark modes, and video tutorials."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Visual icons and assets
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0

  # Videos and local storage
  shared_preferences: ^2.2.3
  carousel_slider: ^5.0.0

  # Supabase Integration
  supabase_flutter: ^2.6.0

  # Monitization and google ads
  google_mobile_ads: ^7.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # PDF generation and launcher dependencies
  pdf: ^3.10.8
  printing: ^5.11.0
  url_launcher: ^6.2.5
  share_plus: ^6.0.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

